import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import "swiper/swiper-bundle.css";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Odonto Prime",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <div className="flex w-full max-w-full">
          <div className="flex flex-col max-w-7xl w-full mx-auto px-4">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
